# Generated by Django 5.2.4 on 2025-07-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logo'),
        ),
        migrations.AddField(
            model_name='brand',
            name='origin',
            field=models.CharField(blank=True, choices=[('1', 'National'), ('2', 'International'), ('3', 'Both')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='rgb_code',
            field=models.CharField(blank=True, help_text='rgb color code', max_length=10, null=True, unique=True),
        ),
    ]
