# Generated by Django 5.2.4 on 2025-07-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_active_brand_logo_brand_origin_color_rgb_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'size', 'color')},
        ),
    ]
