# Generated by Django 5.2.4 on 2025-08-05 17:56

import django.db.models.deletion
import inventory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_tag_product_brand_product_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=models.CharField(
                max_length=7,
                validators=[inventory.validators.validate_hex_color],
                verbose_name="Color Hex",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="inventory.category",
            ),
        ),
    ]
