# Generated by Django 5.2.4 on 2025-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_created_at_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
