# Generated by Django 5.2.4 on 2025-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_total_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_sold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
